### ISSUE TITLE
Mass Effect 2 crashing

### ISSUE THREAD

**Issue by WalrusInAnus** [Erik-JS/masseffect-binkw32#9] opened 2017-02-06 08:17 UTC
I downloaded the archive, copied over the files, and now ME2 is crashing when I start it.
I have both VC++ 2015 packages installed (version 14.0.24210.0).

I looked at EventLog and the error is related to VC++ 2005 (which I do have installed), but the crashing only started after installing the new dlls.
Faulting application name: MassEffect2.exe, version: 1.2.1604.0, time stamp: 0x4bd611db
Faulting module name: MSVCR80.dll, version: 8.0.50727.6229, time stamp: 0x4ec352ab

The log says:
ME2 Autopatcher by Erik JS
Based on original code by Warranty Voider
Addresses loaded from binkw23.dll - OK
Console patch: done
DLC check - searching...
DLC check - position: 0x9584CB
DLC check - patch: done

edit: I run Windows 7 and have administrator account.

**Comment by Erik-JS** [comment] 2017-02-07 10:49
I'm not sure this is caused by the custom binkw32.dll... If you go back to the original binkw32.dll does the game work fine? I assume you already tried to reinstall/repair VC++ 2005.

Currently, there's nothing else I can suggest you that you cannot find in Google. Yes, I'm talking about this:
https://answers.microsoft.com/en-us/windows/forum/all/msvcr80dll-crashing-everything-on-most-machines/0098dd93-016f-49ee-b0a1-c8272bab2785?auth=1

The file seems to be "all over the place" (the actual explanation is in the link above), I noticed that some programs have that file in their own folders. If you want, I can upload some files for testing (but I can't do this until I'm back home).

**Comment by WalrusInAnus** [comment] 2017-02-07 11:07
I ended up reinstalling Windows because something seemed completely FUBAR. In the end, I THINK the crashing was caused by broken coalesced.ini though. According to google I figured I could use Notepad++ to edit it, and that was not true. Oh well. A reinstall never hurts anyway. Why it caused EventLog to display VC errors I don't understand.

Anyway, now with cleanly installed OS and game, I started experimenting gain.
Vanilla game starts just fine, but bitches about the DLCs I downloaded from some EA link. Sounds normal.
When I edit the ini file with Coalesced editor, the game starts just fine too.
BUT
The moment I copy your dlls in the binaries folder, the game does not start at all. No errors, nothing.

I have VC++ 2015 x64 installed. Now I am not entirely sure, but do I also need x86 version? Please confirm.

**Comment by WalrusInAnus** [comment] 2017-02-07 11:13
...sure enough, x86 version was needed. No shit when the game is 32bit. I guess I'm slightly retarded today.
I guess we can close this, heh.

**Comment by Erik-JS** [comment] 2017-02-07 11:40
Yeah, when a DLL is loaded, that DLL becomes part of the program. If the program is 32-bit, it will only run 32-bit code.

I'm closing this issue now.

**Closed as completed by Erik-JS** 2017-02-07 11:40 UTC
