### ISSUE TITLE
Won't start via Origin

### ISSUE THREAD

**Issue by Lombra** [Erik-JS/masseffect-binkw32#10] opened 2017-02-23 01:06 UTC
Trying to launch from Origin does nothing after having applied this patch. Just one second of loading cursor, then nothing. Launching directly from ME2Game.exe does work, however, so I'm not sure what to make of that. Origin uses MassEffect2.exe, I think.

I had a look at #8 and followed the advice and tried some of the alternative versions provided. (maybe they're the current release versions now?) The Visual C++ claims to already be installed, and I made sure to unblock the DLLs.

**Comment by Erik-JS** [comment] 2017-02-23 13:59
Origin needs MassEffect2.exe, but the actual running process after the game has started is ME2Game.exe (it's the largest EXE file). You can directly start ME2Game.exe, but the Origin overlay won't be loaded unless the game is launched from the Origin client.

Did you understand what was happening with #8? Anyway, you shouldn't use the DLL's from there, the latest release compiled under VC 2015 includes the necessary fixes.

Did you check your Documents folder? Is there a binkw32-me2.log (with contents...) after the game fails to start under Origin?

I can't do much when you guys only say "it doesn't work here".  As you saw, some issues were solved without the need of alterations or tweaks in the binkw32's code. I'm not saying it's your PC's fault, but, currently, there really is not much that I can do here besides booting my old PC into Windows 7 and testing the game on my secondary Origin account.

**Comment by Lombra** [comment] 2017-02-23 14:42
Right, it would appear that I have wasted your time. (no sarcasm intended!) It now does work, but I'm not sure why. I was trying (and mostly succeeding) to install the ALOT HD patch, followed by installing this patch when I noticed it was needed to fix the DLC errors. That's when I ran into this issue.

I also tried to install some optional patches from the ALOT package, and that didn't go very well. In the process I discovered some more DLCs that were free to download on Origin. Installing those however made it impossible to apply the optional patch as it complained about game files having been modified, which led me to performing a full reinstall of the game. (this time including the new DLCs I added) Again I applied the ALOT patch, and also the optional patch, this time with more success. Applied your patch, and this time it worked.

So, apart from those additional DLCs, I don't know what the difference would have been this time around. It's possible that something might have gone wrong in the ALOT patching process the last time around, but I wouldn't have thought launching through ME2Game.exe would've worked then.

I can address the rest of your comment, but I'm not sure how relevant it is now that I know it does work.

Not sure if it was implied, but I do use Windows 7, indeed. #8 sounded like a similar issue to mine. What I gathered from the conversation was that admin rights and blocked files were the main theories. I run in admin mode all the time and unblocked the files. I think I looked for the log in the binaries folder, so I might have missed that, then.

I don't really want to do everything again and mess up my game now, but I could see if I can reproduce it on a different PC (Windows 10, though), not installing those extra DLCs.

**Comment by LoD2aef** [comment] 2017-02-23 14:48
Hello people i had problems with ALOT #6 that i didn't accept my DLC (ME2) so i got the new the binkw32.dll from github, but then my origin stop working for ME2 saying it's a invald dll i had so after som talk and trying we found the answar. but before that fast backgrund about my setup 1: Os is windows 10 pro 2: i have no other texture mods, only nominigames and short loading time mods 3: i run the setup of ALOT MEM and all worked (but it don't accept my dlc) so i get the binkw32.dll from r2 and it don't work. but with the older version of binkw32.dll from r1 it work for me

**Comment by Erik-JS** [comment] 2017-02-24 03:13
As the issue is now solved, I'm closing it now.

Regarding @LoD2aef's comment, if anyone wants to use r1, you must install [Visual C++ 2012 runtimes](http://www.microsoft.com/en-us/download/details.aspx?id=30679).
Keep in mind that r1 will always attempt to create a log file in the game's folder, and it'll crash if the file cannot be created for whatever reason. On the other hand, r2 (the current release as of this writing) will never crash because of log creation error.

**Closed as completed by Erik-JS** 2017-02-24 03:13 UTC
